# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    #driver: "imagick"
    # valid drivers options include "gd" or "gmagick" or "imagick"
    #resolvers:
        #default:
            #web_path:
                #web_root: "%kernel.project_dir%/public"
                #cache_prefix: media/cache
    #loaders:
        #default:
            #filesystem:
                #data_root: "%kernel.project_dir%/public/upload/images"
                #bundle_resources:
                    #enabled: true

    #data_loader: default
    #cache: default
    filter_sets:
        cache: ~
        thumb:
            quality: 75
            filters:
                #rotate:
                    #angle: 180
                #auto_rotate: ~
                #mobile_auto_rotate: ~
                thumbnail:
                    size:          [360, 230]
                    mode:          outbound
                    allow_upscale: true
        medium:
            quality: 75
            filters:
                #rotate:
                    #angle: 180
                #auto_rotate: ~
                #mobile_auto_rotate: ~
                thumbnail:
                    size:          [800, 530]
                    mode:          outbound
                    allow_upscale: true
